## Official Source: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
# 
# Datadog Agent with Logs, APM, Processes, NPM, Events, System Probe, Security(CSPM+CWS), ClusterAgent, OrchestratorExplorer (Live Containers), Check Runners, USM, DSM , Remote config enabled

# targetSystem -- Target OS for this deployment (possible values: linux, windows)
targetSystem: "linux"

## Edit this
datadog:
  apiKey: <DATADOG_API_KEY> #<<<<<ENTER YOUR API KEY HERE 
  appKey: <DATADOG_APP_KEY> #<<<<<ENTER YOUR APP KEY HERE
  clusterName: <CLUSTER_NAME> #<<<<<ENTER YOUR Cluster Name HERE
  site: datadoghq.com  #<<<<<ENTER YOUR SITE (US1)
  collectEvents: true
  tags: []
  kubelet:
    tlsVerify: "false"

## Logs 
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: true

## APM
  apm:
    instrumentation:
      enabled: true
    portEnabled: true
    port: 8126
    socketEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/

## Process Monitoring
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enableTCPQueueLength: true
    enableOOMKill: true
    collectDNSStats: true

## Kubernetes Orchestrator
  orchestratorExplorer:
    enabled: true

## Network Performance Monitoring
  networkMonitoring:
    enabled: true

## Universal Service Monitoring
  serviceMonitoring:
    enabled: true

## Enable Data Streams Monitoring
  dataStreamsMonitoring:
    enabled: true

## Enable ASM SCA CodeSec
  asm:
    threats:
      enabled: true
    sca:
      enabled: true
    iast:
      enabled: true

## Cloud Security Posture Management
  securityAgent:
    compliance:
      enabled: true

## Cloud Workload Security
    runtime:
      enabled: true
      fimEnabled: true  ##Set to true to enable Cloud Workload Security (CWS) File Integrity Monitoring
      network: 
        enabled: true     ##Set to true to enable the collection of CWS network events
    sbom:
      containerImage:
        enabled: true
      host:
        enabled: true

## Remote Configuration
remoteConfiguration:
  enabled: true

## View Agent Config from Datadog UI
inventories_configuration_enabled: true

## Kubernetes Cluster Agent
clusterAgent:
  enabled: true
  replicas: 2
  rbac:
    create: true
    serviceAccountName: default
  metricsProvider:
    enabled: true
    createReaderRbac: true
    useDatadogMetrics: true
    service:
      type: ClusterIP
      port: 8443
  admissionController:
    enabled: true
    mutateUnlabelled: true
agents:
  rbac:
    create: true
    serviceAccountName: default
# clusterChecksRunner:
#   enabled: true
#   rbac:
#     create: true
#     serviceAccountName: default
#   replicas: 2

