apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_APP_KEY>
  features:
    logCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
      unixDomainSocketConfig:
        enabled: true
    cspm:
      enabled: true
    cws:
      enabled: true
    npm:
      enabled: true
    usm:
      enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
          http:
            enabled: true
    remoteConfiguration:
      enabled: true
    sbom:
      enabled: true
    externalMetricsServer:
      enabled: true
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
